language: cpp

matrix:
  include:
    - os: osx
      env: 
        - OUTPUT_ZIP_FILE=YUView_mac.zip
    - os: windows
      env: 
        - OUTPUT_ZIP_FILE=YUView_win.zip
    - os: linux
      env:
        - OUTPUT_ZIP_FILE=App.app
      dist:
        - trusty
compiler: 
  - gcc

branches:
  except:
    - gh-pages

before_install:
  - eval "${MATRIX_EVAL}"
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository ppa:forkotov02/opt-qt-5.11.1-trusty -y
      sudo apt-get update -qq
      # On linux also get a newer g++. The old one won't work.
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt-get update -qq
      # On linux, also get the linuxdeployqt tool to build the Appimage
      wget https://github.com/probonopd/linuxdeployqt/releases/download/6/linuxdeployqt-6-x86_64.AppImage
      chmod a+x linuxdeployqt-6-x86_64.AppImage
    fi
  
install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      # Qt Base
      cd /Users/travis/build
      curl -L https://github.com/ChristianFeldmann/YUViewQt/releases/download/QtBase-5.13.1/Qtbase-5.13.1_mac.zip -o Qt.zip
      unzip -q -a Qt.zip
      cd $TRAVIS_BUILD_DIR
      cd ..
      export PATH=/Users/travis/build/Qt/bin:$PATH
      # QtTools 
      curl -L https://github.com/ChristianFeldmann/YUViewQt/releases/download/QtTools-5.13.1/QtTools-5.13.1_mac.zip -o QtTools.zip
      unzip -q -a QtTools.zip
      cd QtTools
      make install
      cd ..
      # QtCharts
      curl -L https://github.com/ChristianFeldmann/YUViewQt/releases/download/QtCharts-5.13.1/QtCharts-5.13.1_mac.zip -o QtCharts.zip
      unzip -q -a QtCharts.zip
      ls -l
      cd QtCharts
      make install
      cd ..
      # libde265
      curl -L https://github.com/ChristianFeldmann/libde265/releases/download/v1.1/libde265.dylib -o libde265-internals.dylib
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      cd /c/Users/travis/build
      curl -L https://github.com/ChristianFeldmann/YUViewQt/releases/download/QtBase-5.13.1/Qtbase-5.13.1_win.zip -o Qt.zip
      unzip -q -a Qt.zip
      cd $TRAVIS_BUILD_DIR
      cd ..
      curl -L https://github.com/ChristianFeldmann/YUViewQt/releases/download/QtCharts-5.13.1/QtCharts-5.13.1_win.zip -o QtCharts.zip
      unzip -q -a QtCharts.zip
      curl -L https://github.com/ChristianFeldmann/YUViewQt/releases/download/QtTools-5.13.1/QtTools-5.13.1_win.zip -o QtTools.zip
      unzip -q -a QtTools.zip
      curl -L -o libde265.dll https://github.com/ChristianFeldmann/libde265/releases/download/v1.1/libde265.dll
      ls -l
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install -qq qt511base; source /opt/qt511/bin/qt511-env.sh
      sudo apt-get install -qq g++-8
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
    fi

script:
  - cd $TRAVIS_BUILD_DIR
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      ./buildWindows.bat
    else
      qmake -config release
      make -j 2
    fi

after_success:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      # Mac: build an "app" file
      $TRAVIS_BUILD_DIR/../Qttools/bin/macdeployqt build/release/YUView.app -always-overwrite -verbose=2
      # check what YUView is linking against
      otool -L build/release/YUView.app/Contents/MacOs/YUView
      # copy the libde265 library
      cp $TRAVIS_BUILD_DIR/../libde265-internals.dylib build/release/YUView.app/Contents/MacOS/.
      cd build/release
      # Zip
      zip -r ../../YUView-MacOs.zip YUView.app
      if [ ${TRAVIS_BRANCH} = "master" ]; then ./deployment/deploy_to_github.sh; fi
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      make INSTALL_ROOT=appdir install
      ./linuxdeployqt-6-x86_64.AppImage appdir/usr/local/share/applications/de.rwth_aachen.ient.YUView.desktop -appimage
    fi
  
before_deploy:
  # not needed?
deploy:
  # we could also put the package somewhere else

