language: cpp

matrix:
  include:
    - os: osx
      env: 
        - OUTPUT_ZIP_FILE=YUView_mac.zip
    - os: windows
      env: 
        - OUTPUT_ZIP_FILE=YUView_win.zip
    - os: linux
      env:
        - OUTPUT_ZIP_FILE=App.app
      dist:
        - trusty
compiler: 
  - gcc

branches:
  except:
    - gh-pages

before_install:
  - eval "${MATRIX_EVAL}"
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository ppa:forkotov02/opt-qt-5.11.1-trusty -y
      sudo apt-get update -qq
      # On linux also get a newer g++. The old one won't work.
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt-get update -qq
      # On linux, also get the linuxdeployqt tool to build the Appimage
      wget https://github.com/probonopd/linuxdeployqt/releases/download/6/linuxdeployqt-6-x86_64.AppImage
      chmod a+x linuxdeployqt-6-x86_64.AppImage
    fi
  
install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cd /Users/travis/build
      curl -L https://github.com/ChristianFeldmann/YUViewQt/releases/download/QtBase-5.13.1/Qtbase-5.13.1_mac.zip -o Qt.zip
      unzip -q -a Qt.zip
      cd $TRAVIS_BUILD_DIR
      curl -L https://github.com/ChristianFeldmann/YUViewQt/releases/download/QtTools-5.13.1/QtTools-5.13.1_mac.zip -o QtTools.zip
      unzip -q -a QtTools.zip
      cd QtTools
      make install
      cd ..
      curl -L https://github.com/ChristianFeldmann/YUViewQt/releases/download/QtCharts-5.13.1/QtCharts-5.13.1_mac.zip -o QtCharts.zip
      unzip -q -a QtCharts.zip
      ls -l
      cd QtCharts
      make install
      cd ..
      export PATH=/Users/travis/build/Qt/bin:$PATH
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      cd /c/Users/travis/build
      curl -L https://github.com/ChristianFeldmann/YUViewQt/releases/download/QtBase-5.13.1/Qtbase-5.13.1_win.zip -o Qt.zip
      unzip -q -a Qt.zip
      cd $TRAVIS_BUILD_DIR
      curl -L https://github.com/ChristianFeldmann/YUViewQt/releases/download/QtCharts-5.13.1/QtCharts-5.13.1_win.zip -o QtCharts.zip
      unzip -q -a QtCharts.zip
      curl -L https://github.com/ChristianFeldmann/YUViewQt/releases/download/QtTools-5.13.1/QtTools-5.13.1_win.zip -o QtTools.zip
      unzip -q -a QtTools.zip
      curl -L -o libde265.dll https://github.com/ChristianFeldmann/libde265/releases/download/v1.1/libde265.dll
      ls -l
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install -qq qt511base; source /opt/qt511/bin/qt511-env.sh
      sudo apt-get install -qq g++-8
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
    fi

script:
  - cd $TRAVIS_BUILD_DIR
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      ./buildWindows.bat
    else
      qmake -config release
      make -j 2
    fi
  - ls -alh
  - ls -alh build
  - ls -alh build/release

after_success:
  # Mac: build an "app" file
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then /usr/local/opt/qt5/bin/macdeployqt build/release/YUView.app -always-overwrite -verbose=2; fi
  # check what YUView is linking against
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then otool -L build/release/YUView.app/Contents/MacOs/YUView; fi
  # copy the libde265 library
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cp libde265/libde265-internals.dylib build/release/YUView.app/Contents/MacOS/.; fi
  # prepare zip package
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cd build/release; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then zip -r ../../YUView-MacOs.zip YUView.app; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cd ../..; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" AND ${TRAVIS_BRANCH} = "master" ]; then ./deployment/deploy_to_github.sh; fi
  # Linux: Build the Appimage
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make INSTALL_ROOT=appdir install; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./linuxdeployqt-6-x86_64.AppImage appdir/usr/local/share/applications/de.rwth_aachen.ient.YUView.desktop -appimage; fi

before_deploy:
  # not needed?
deploy:
  # we could also put the package somewhere else

